apiVersion: v1
kind: Secret
metadata:
  name: auction-notifications-secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: "secure_password_here"
  MAIL_USERNAME: "your-email@gmail.com"
  MAIL_PASSWORD: "your-app-password"
  APNS_KEY_ID: "YOUR_KEY_ID"
  APNS_TEAM_ID: "YOUR_TEAM_ID"