spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - openid
              - email
              - profile
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/facebook
            scope:
              - email
              - public_profile

jwt:
  secret: mySecretKeyForJWTWhichShouldBeAtLeast256BitsLong
  expiration: 86400000  # 24 hours
  refreshExpiration: 604800000  # 7 days