server:
  port: 8080

spring:
  datasource:
    url: "jdbc:h2:mem:testdb"
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.SnakeCasePhysicalNamingStrategy
  flyway:
    enabled: false
  web:
    resources:
      static-locations: classpath:/static/
  cache:
    type: none
  redis:
    host: localhost
    port: 6379

# JWT Configuration
jwt:
  secret: supersecretjwtkeythatislongenough
  expiration: 86400000
  refresh:
    expiration: 604800000