spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: analytics-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.auctionflow.core.domain.events"
  redis:
    host: localhost
    port: 6379

ml:
  service:
    url: http://localhost:5000  # Python ML service URL

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    export:
      prometheus:
        enabled: true