apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "auction-api.fullname" . }}-config
  labels:
    {{- include "auction-api.labels" . | nindent 4 }}
data:
  application.yml: |
{{ toYaml .Values.config | indent 4 }}