spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.auctionflow.core.domain.events"
  redis:
    host: localhost
    port: 6379
  websocket:
    stomp:
      broker-relay: false
  datasource:
    url: jdbc:postgresql://localhost:5432/auctionflow
    username: auctionflow
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-app-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

firebase:
  config:
    path: classpath:firebase-service-account.json

apns:
  key-id: YOUR_KEY_ID
  team-id: YOUR_TEAM_ID
  topic: com.auctionflow.app
  key-path: classpath:apns-key.p8

server:
  port: 8082