spring:
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:postgresql://localhost:5432/auctionflow
    username: auctionflow
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when_authorized
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

 otel:
   service:
     name: auction-payments
   traces:
     exporter: jaeger
     sampler: parentbased_always_on
     sampler.arg: 0.1
   exporter:
     jaeger:
       endpoint: http://localhost:14268/api/traces

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 60s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        recordExceptions:
          - org.springframework.web.client.RestClientException
          - java.io.IOException
          - java.util.concurrent.TimeoutException
        ignoreExceptions:
          - io.github.resilience4j.circuitbreaker.CallNotPermittedException
    instances:
      stripeGateway:
        baseConfig: default
        waitDurationInOpenState: 30s
        failureRateThreshold: 40
      paypalGateway:
        baseConfig: default
        waitDurationInOpenState: 30s
        failureRateThreshold: 40
  bulkhead:
    instances:
      paymentGateway:
        maxConcurrentCalls: 10
        maxWaitDuration: 50ms